import { ModelItem } from '../../types';

export const initialModelData: ModelItem[] = [
  // ==========================================
  // 图片生成模型 (6个)
  // ==========================================
  {
    id: 'nano-banana-2-lite',
    name: 'Nano Banana 2 Lite',
    vendor: 'Nano Banana AI',
    category: 'image',
    logoGradient: 'from-amber-400 via-yellow-500 to-amber-600',
    version: 'v2.1.0',
    updateTime: '2026-07-15',
    badgeType: '稳定版',
    description: '超高并发亚秒级生成引擎，专为小红书与电商大量商品图、变体图打造。',
    tags: ['极速', '商品图', '批量出图', '高清'],
    scenarios: ['快速生成商品图', '批量出图', '主图变体测试', '爆款SKU背景快速生成'],
    ratings: {
      quality: 4.2,
      speed: 5.0,
      cost: 1.0,
      recommendation: 4.8
    },
    capabilities: ['支持中文', '支持英文', '支持背景替换', '支持超清', '支持商品一致性'],
    outputSizes: ['1024x1024 (1:1)', '3:4', '9:16', '16:9'],
    outputFormats: ['WEBP', 'PNG', 'JPG'],
    recommendedWorkflow: '小红书网感主图批量生成 / 电商SKU背景自动替换',
    costDesc: '￥0.008 / 张 (极低成本)',
    status: 'connected',
    isDefault: false,
    isFavorite: true,
    lastUsedTime: '10 分钟前',
    apiKey: 'nb_live_28947298374982374',
    baseUrl: 'https://api.nanobanana.ai/v2',
    modelCode: 'nano-banana-2-lite',
    timeoutSeconds: 15,
    maxRetries: 3,
    concurrency: 20
  },
  {
    id: 'nano-banana-pro',
    name: 'Nano Banana Pro',
    vendor: 'Nano Banana AI',
    category: 'image',
    logoGradient: 'from-amber-500 via-orange-600 to-red-600',
    version: 'v3.0.2',
    updateTime: '2026-07-18',
    badgeType: '稳定版',
    description: '专为营销海报与高定品牌视觉设计的旗舰级图像大模型，光影与纹理感极佳。',
    tags: ['高质量', '海报', '广告素材', '写实', '运营推荐'],
    scenarios: ['营销海报', '高质量商品图', '广告素材', '美妆高定KV大片'],
    ratings: {
      quality: 4.9,
      speed: 4.0,
      cost: 3.0,
      recommendation: 5.0
    },
    capabilities: ['支持中文', '支持英文', '支持图片编辑', '支持背景替换', '支持局部重绘', '支持超清', '支持人物一致性', '支持商品一致性'],
    outputSizes: ['1:1', '3:4', '4:3', '9:16', '16:9', '21:9 UltraWide'],
    outputFormats: ['PNG', 'WEBP', 'TIFF'],
    recommendedWorkflow: '美妆高端KV大牌海报 / 小红书爆款图文封面渲染',
    costDesc: '￥0.05 / 张',
    status: 'connected',
    isDefault: false,
    isFavorite: false,
    lastUsedTime: '2 小时前',
    apiKey: 'nb_pro_9938120391283',
    baseUrl: 'https://api.nanobanana.ai/v3',
    modelCode: 'nano-banana-pro-v3',
    timeoutSeconds: 30,
    maxRetries: 3,
    concurrency: 10
  },
  {
    id: 'imagen-4',
    name: 'Imagen 4',
    vendor: 'Google Cloud',
    category: 'image',
    logoGradient: 'from-blue-600 via-indigo-500 to-cyan-500',
    version: 'v4.0.0',
    updateTime: '2026-07-20',
    badgeType: '稳定版',
    description: '综合表现出色的全能型图像生成引擎，语义理解精准，光影色彩自然真实。',
    tags: ['综合优秀', '写实', '高清', '封面', '运营推荐'],
    scenarios: ['日常图片生成', '综合表现优秀', '品牌图文视觉', '小红书种草卡片'],
    ratings: {
      quality: 4.8,
      speed: 4.5,
      cost: 2.5,
      recommendation: 4.9
    },
    capabilities: ['支持中文', '支持英文', '支持图片编辑', '支持背景替换', '支持局部重绘', '支持超清', '支持人物一致性'],
    outputSizes: ['1:1', '3:4', '4:3', '9:16', '16:9'],
    outputFormats: ['PNG', 'JPEG', 'WEBP'],
    recommendedWorkflow: '全平台通用主图与图文爆款素材拆解生成',
    costDesc: '￥0.03 / 张',
    status: 'connected',
    isDefault: true, // 默认图片模型
    isFavorite: true,
    lastUsedTime: '刚刚',
    apiKey: 'AIzaSy_GCLOUD_IMAGEN_4_PRESET_ACTIVE',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    modelCode: 'imagen-4.0-generate-001',
    timeoutSeconds: 30,
    maxRetries: 3,
    concurrency: 15
  },
  {
    id: 'imagen-4-ultra',
    name: 'Imagen 4 Ultra',
    vendor: 'Google Cloud',
    category: 'image',
    logoGradient: 'from-purple-600 via-indigo-600 to-blue-700',
    version: 'v4.1-ultra-preview',
    updateTime: '2026-07-22',
    badgeType: '预览版',
    description: '顶级奢华质感渲染，商业摄影级景深、光泽度与肌理细致入微，适合顶级品牌KV。',
    tags: ['高端广告', '品牌 KV', '电商主图', '人像', '写实', '运营推荐'],
    scenarios: ['高端广告', '品牌 KV', '电商主图', '高定杂志封面', '奢侈品展示'],
    ratings: {
      quality: 5.0,
      speed: 3.5,
      cost: 4.5,
      recommendation: 4.9
    },
    capabilities: ['支持中文', '支持英文', '支持图片编辑', '支持背景替换', '支持局部重绘', '支持超清', '支持人物一致性', '支持商品一致性'],
    outputSizes: ['2048x2048 Ultra', '3:4 Ultra', '16:9 8K Ultra'],
    outputFormats: ['PNG (无损)', 'TIFF', 'WEBP'],
    recommendedWorkflow: '高端美妆奢侈品视觉定调 / 官方大牌主图画册精打',
    costDesc: '￥0.12 / 张',
    status: 'connected',
    isDefault: false,
    isFavorite: true,
    lastUsedTime: '1 天前',
    apiKey: 'AIzaSy_GCLOUD_ULTRA_KEYS',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    modelCode: 'imagen-4.1-ultra-preview',
    timeoutSeconds: 45,
    maxRetries: 2,
    concurrency: 5
  },
  {
    id: 'imagen-4-fast',
    name: 'Imagen 4 Fast',
    vendor: 'Google Cloud',
    category: 'image',
    logoGradient: 'from-cyan-500 via-teal-500 to-emerald-600',
    version: 'v4.0-fast',
    updateTime: '2026-07-10',
    badgeType: '稳定版',
    description: '亚秒级极速预览引擎，适合在创意拆解阶段快速生成多选项方案验证。',
    tags: ['极速', '方案验证', '快速预览', '批量'],
    scenarios: ['快速预览', '方案验证', '创意草稿快速生成', '分镜脚本意图确认'],
    ratings: {
      quality: 4.0,
      speed: 5.0,
      cost: 1.0,
      recommendation: 4.5
    },
    capabilities: ['支持中文', '支持英文', '支持背景替换', '支持超清'],
    outputSizes: ['512x512', '1024x1024', '3:4'],
    outputFormats: ['WEBP', 'JPG'],
    recommendedWorkflow: '脚本分镜AI快速试样 / 创意AB测试快速出稿',
    costDesc: '￥0.005 / 张 (极高性价比)',
    status: 'connected',
    isDefault: false,
    isFavorite: false,
    lastUsedTime: '3 小时前',
    apiKey: 'AIzaSy_GCLOUD_FAST_KEYS',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    modelCode: 'imagen-4.0-fast-001',
    timeoutSeconds: 10,
    maxRetries: 3,
    concurrency: 30
  },
  {
    id: 'gpt-image-2',
    name: 'GPT Image 2',
    vendor: 'OpenAI',
    category: 'image',
    logoGradient: 'from-emerald-600 via-teal-700 to-zinc-900',
    version: 'v2.0.0',
    updateTime: '2026-06-28',
    badgeType: '稳定版',
    description: '强大图文多模态交互图像模型，支持极其复杂的文本提示词理解与多图融合编辑。',
    tags: ['创意设计', '复杂图片编辑', '文字精准', '局部重绘'],
    scenarios: ['创意设计', '复杂图片编辑', '海报艺术字设计', '跨风格二次合成'],
    ratings: {
      quality: 4.7,
      speed: 4.0,
      cost: 3.5,
      recommendation: 4.6
    },
    capabilities: ['支持中文', '支持英文', '支持图片编辑', '支持背景替换', '支持局部重绘', '支持人物一致性'],
    outputSizes: ['1024x1024', '1792x1024', '1024x1792'],
    outputFormats: ['PNG', 'WEBP'],
    recommendedWorkflow: '复杂海报多层图文组合 / 智能二次精准修图',
    costDesc: '￥0.08 / 张',
    status: 'pending', // 待配置
    isDefault: false,
    isFavorite: false,
    lastUsedTime: '未配置',
    apiKey: '',
    baseUrl: 'https://api.openai.com/v1/images',
    modelCode: 'gpt-image-2-dalle',
    timeoutSeconds: 30,
    maxRetries: 2,
    concurrency: 5
  },

  // ==========================================
  // 视频生成模型 (5个)
  // ==========================================
  {
    id: 'omni-flash',
    name: 'Omni Flash',
    vendor: 'Google DeepMind',
    category: 'video',
    logoGradient: 'from-violet-600 via-purple-600 to-indigo-800',
    version: 'v1.2.0',
    updateTime: '2026-07-19',
    badgeType: '稳定版',
    description: '全能多模态超低延迟视频渲染引擎，擅长短视频动效与高质感质地流动。',
    tags: ['极速', '短视频', '动态镜头', '运营推荐'],
    scenarios: ['快速生成', '短视频', '动态卡点镜头', '质感流体展示'],
    ratings: {
      quality: 4.6,
      speed: 4.9,
      cost: 2.0,
      recommendation: 4.8
    },
    capabilities: ['支持中文', '支持英文', '支持人物一致性', '支持商品一致性', '支持超清'],
    outputSizes: ['1080x1920 (9:16)', '1920x1080 (16:9)'],
    outputFormats: ['MP4 (H.264)', 'MOV'],
    recommendedWorkflow: '抖音高频质感短视频 / 小红书动态封面与流动特写',
    costDesc: '￥0.15 / 秒',
    status: 'connected',
    isDefault: false,
    isFavorite: true,
    lastUsedTime: '15 分钟前',
    apiKey: 'omni_flash_preprovisioned_2026',
    baseUrl: 'https://api.deepmind.google/omni/v1',
    modelCode: 'omni-flash-v1.2',
    timeoutSeconds: 45,
    maxRetries: 3,
    concurrency: 10
  },
  {
    id: 'veo-3-1-preview',
    name: 'Veo 3.1 Preview',
    vendor: 'Google DeepMind',
    category: 'video',
    logoGradient: 'from-fuchsia-600 via-purple-600 to-pink-600',
    version: 'v3.1-preview',
    updateTime: '2026-07-21',
    badgeType: '预览版',
    description: '谷歌最新 4K 120fps 商业级视频生成大模型，光影动态自然，镜头语言细腻。',
    tags: ['高质量广告', '品牌宣传', '4K高清', '电影感', '运营推荐'],
    scenarios: ['高质量广告', '品牌宣传', '高定产品镜头特写', '商业宣传片'],
    ratings: {
      quality: 5.0,
      speed: 3.8,
      cost: 4.0,
      recommendation: 4.9
    },
    capabilities: ['支持中文', '支持英文', '支持人物一致性', '支持商品一致性', '支持超清', '支持长视频'],
    outputSizes: ['4K UHD Cinema', '1080p Vertical 9:16'],
    outputFormats: ['MP4 (ProRes Quality)', 'MOV'],
    recommendedWorkflow: '品牌高定广告片 / 商业微距质感慢动作镜头渲染',
    costDesc: '￥0.45 / 秒',
    status: 'connected',
    isDefault: false,
    isFavorite: true,
    lastUsedTime: '1 小时前',
    apiKey: 'veo_31_commercial_key',
    baseUrl: 'https://api.deepmind.google/veo/v3.1',
    modelCode: 'veo-3.1-preview-4k',
    timeoutSeconds: 90,
    maxRetries: 2,
    concurrency: 3
  },
  {
    id: 'veo-3-1-fast-preview',
    name: 'Veo 3.1 Fast Preview',
    vendor: 'Google DeepMind',
    category: 'video',
    logoGradient: 'from-pink-500 via-rose-600 to-purple-700',
    version: 'v3.1-fast',
    updateTime: '2026-07-16',
    badgeType: '测试版',
    description: 'Veo 3.1 极速版，大幅缩短生成排队时间，适合脚本分镜连贯性动态测试。',
    tags: ['快速测试', '极速', '动态分镜', '效果初筛'],
    scenarios: ['快速测试', '动态分镜预演', '效果初筛', '预演样片导出'],
    ratings: {
      quality: 4.2,
      speed: 5.0,
      cost: 1.5,
      recommendation: 4.6
    },
    capabilities: ['支持中文', '支持英文', '支持超清'],
    outputSizes: ['720p Fast', '1080p 9:16'],
    outputFormats: ['MP4'],
    recommendedWorkflow: '分镜拍摄方案AI动态样片速出与运镜路线确认',
    costDesc: '￥0.08 / 秒',
    status: 'connected',
    isDefault: false,
    isFavorite: false,
    lastUsedTime: '5 小时前',
    apiKey: 'veo_fast_test_key',
    baseUrl: 'https://api.deepmind.google/veo/v3.1fast',
    modelCode: 'veo-3.1-fast-preview',
    timeoutSeconds: 20,
    maxRetries: 3,
    concurrency: 15
  },
  {
    id: 'seedance-2-0',
    name: 'Seedance 2.0',
    vendor: 'Seedance Studio',
    category: 'video',
    logoGradient: 'from-blue-600 via-cyan-600 to-teal-700',
    version: 'v2.0.4',
    updateTime: '2026-07-22',
    badgeType: '稳定版',
    description: '顶级电影级画面渲染，动态物理仿真优秀，镜头拉伸与粒子特效极度逼真。',
    tags: ['电影级画面', '营销广告', '高质量', '运营推荐'],
    scenarios: ['电影级画面', '营销广告', '3D光影质感大片', '爆款视频复刻'],
    ratings: {
      quality: 4.9,
      speed: 4.2,
      cost: 3.5,
      recommendation: 5.0
    },
    capabilities: ['支持中文', '支持英文', '支持背景替换', '支持人物一致性', '支持商品一致性', '支持超清', '支持长视频'],
    outputSizes: ['16:9 4K Cinema', '9:16 1080p', '1:1 Square'],
    outputFormats: ['MP4', 'ProRes 422 HQ'],
    recommendedWorkflow: '美妆爆款质感镜头一键生成 / 爆款广告完美复刻',
    costDesc: '￥0.30 / 秒',
    status: 'connected',
    isDefault: true, // 默认视频模型
    isFavorite: true,
    lastUsedTime: '30 分钟前',
    apiKey: 'sd_20_studio_live_token',
    baseUrl: 'https://api.seedance.ai/v2',
    modelCode: 'seedance-2.0-pro-cinema',
    timeoutSeconds: 60,
    maxRetries: 3,
    concurrency: 8
  },
  {
    id: 'seedance-2-0-fast',
    name: 'Seedance 2.0 Fast',
    vendor: 'Seedance Studio',
    category: 'video',
    logoGradient: 'from-teal-500 via-emerald-600 to-cyan-700',
    version: 'v2.0-fast',
    updateTime: '2026-07-14',
    badgeType: '稳定版',
    description: 'Seedance 2.0 极速轻量引擎，平衡了渲染速度与粒子流动感，快速输出营销视频。',
    tags: ['快速出片', '高效率', '抖音爆款', '信息流'],
    scenarios: ['快速出片', '批量营销视频', '信息流广告', '短视频快速合成'],
    ratings: {
      quality: 4.5,
      speed: 4.8,
      cost: 2.0,
      recommendation: 4.7
    },
    capabilities: ['支持中文', '支持英文', '支持商品一致性', '支持超清'],
    outputSizes: ['9:16 Vertical Short', '16:9 Standard'],
    outputFormats: ['MP4'],
    recommendedWorkflow: '批量信息流投流素材视频快速成片',
    costDesc: '￥0.12 / 秒',
    status: 'connected',
    isDefault: false,
    isFavorite: false,
    lastUsedTime: '1 天前',
    apiKey: 'sd_fast_live_token',
    baseUrl: 'https://api.seedance.ai/v2fast',
    modelCode: 'seedance-2.0-fast',
    timeoutSeconds: 25,
    maxRetries: 3,
    concurrency: 12
  }
];
